- alias: Turn off the heating when away
  trigger:
    - platform: state
      entity_id: person.abi
      to: 'away'
    - platform: time_pattern
      minutes: '5'
    - platform: state
      entity_id: person.toby
      to: 'away'
    - platform: time_pattern
      minutes: '5'
  condition:
    - condition: state
      entity_id: person.abi
      state: 'away'
    - condition: state
      entity_id: person.toby
      state: 'away'
  action:
    service: climate.set_operation_mode
    data:
      entity_id: climate.living_room
      operation_mode: 'off'