### Livingroom Automations ###

# Livingroom Sensor Automations
- alias: Turn on livingroom lights morning
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.living_room_light_level
      below: '3'
    - condition: state
      entity_id: light.living_room_lamp
      state: 'off'
    - condition: state
      entity_id: light.living_room_pendant
      state: 'off'
    - condition: state
      entity_id: switch.christmas_lights
      state: 'off'
    - condition: time
      after: '07:00:00'
      before: '09:59:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.living_room_lamp
    data_template:
      brightness: 130
      color_temp: 318
      transition: 5

- alias: Turn on livingroom lights day
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.living_room_light_level
      below: '5'
    - condition: state
      entity_id: light.living_room_lamp
      state: 'off'
    - condition: state
      entity_id: light.living_room_pendant
      state: 'off'    
    - condition: state
      entity_id: switch.christmas_lights
      state: 'off' 
    - condition: time
      after: '09:00:00'
      before: '23:29:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.living_room_lamp
    data_template:
      brightness: 254
      color_temp: 318
      transition: 5

- alias: Turn on livingroom lights night
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.living_room_light_level
      below: '2'
    - condition: state
      entity_id: light.living_room_lamp
      state: 'off'
    - condition: state
      entity_id: light.living_room_pendant
      state: 'off'
    - condition: state
      entity_id: switch.christmas_lights
      state: 'off'
    - condition: time
      after: '23:30:00'
      before: '06:59:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.living_room_lamp
    data_template:
      brightness: 40
      color_temp: 318
      transition: 30

# Livingroom Away Mode
- alias: Turn on livingroom lights away mode
  trigger:
    platform: state
    entity_id: sun.sun
    to: 'below_horizon'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.living_room_light_level
      below: '2'
    - condition: state
      entity_id: sensor.toby_connected_ap
      state: 'Offline'
    - condition: state
      entity_id: sensor.abi_connected_ap
      state: 'Offline'
  action:
    service: homeassistant.turn_on
    entity_id: light.living_room_lamp
    data_template:
      brightness: 130
      color_temp: 318
      transition: 30
