# office Sensor Automations
- alias: Turn on office light night
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion_sensor
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.office_shadow