# office Sensor Automations
- alias: Turn on office light morning
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion_sensor
    to: 'on'
  condition:
  - below: '3'
    condition: numeric_state
    entity_id: sensor.office_light_level
  - condition: state
    entity_id: light.office_shadow
    state: 'off'
  - condition: time
    after: '07:00:00'
    before: '08:59:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.office_shadow
    data_template:
      brightness: 130
      color_temp: 318
      transition: 5

- alias: Turn on office light day
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion_sensor
    to: 'on'
  condition:
  - below: '6'
    condition: numeric_state
    entity_id: sensor.office_light_level
  - condition: state
    entity_id: light.office_shadow
    state: 'off'
  - condition: time
    after: '09:00:00'
    before: '23:29:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.office_shadow
    data_template:
      brightness: 254
      color_temp: 318
      transition: 5

- alias: Turn on office light night
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion_sensor
    to: 'on'
  condition:
  - below: '2'
    condition: numeric_state
    entity_id: sensor.office_light_level
  - condition: state
    entity_id: light.office_shadow
    state: 'off'
  - condition: time
    after: '23:30:00'
    before: '06:59:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.office_shadow
    data_template:
      brightness: 40
      color_temp: 318
      transition: 30

- alias: Turn off office lights
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion_sensor
      to: 'off'
    - platform: time_pattern
      minutes: '60'
    - platform: state
      entity_id: binary_sensor.office_motion_sensor
      to: 'off'
    - platform: time_pattern
      minutes: '120'
    - platform: state
      entity_id: binary_sensor.office_motion_sensor
      to: 'off'
    - platform: time_pattern
      minutes: '180'
    - platform: state
      entity_id: binary_sensor.office_motion_sensor
      to: 'off'
    - platform: time_pattern
      minutes: '240'
  condition:
    - condition: state
      entity_id: binary_sensor.office_motion_sensor
      state: 'off'
#    - platform: time_pattern
#      minutes: '60'
  action:
    service: homeassistant.turn_off
    entity_id: light.office_shadow
    data_template:
      transition: 30