# Philips Hue Motion Sensor - RestAPI (Custom-Component)
## https://github.com/robmarkcole/Hue-sensors-HASS ##
## https://community.home-assistant.io/t/map-values-for-an-input-select/94354/20 ##
- platform: huesensor

- platform: template
  sensors:
# Kitchen Sensor
    kitchen_temperature:
      friendly_name: 'Kitchen temperature'
      value_template: '{{state_attr("binary_sensor.kitchen_motion_sensor", "temperature")}}'
      unit_of_measurement: °C
      device_class: temperature

    kitchen_light_level:
      friendly_name: 'Kitchen light level'
      value_template: '{{state_attr("binary_sensor.kitchen_motion_sensor", "lx")}}'
      unit_of_measurement: lux

    kitchen_battery_level:
      friendly_name: 'Kitchen battery level'
      value_template: '{{state_attr("binary_sensor.kitchen_motion_sensor", "battery")}}'
      unit_of_measurement: '%'

    kitchen_motion_sensor_sensitivity:
      friendly_name: 'Kitchen sensitivity'
      value_template: >
        {{state_attr('binary_sensor.kitchen_motion_sensor','sensitivity')}}

    kitchen_motion_sensor_threshold:
      friendly_name: 'Kitchen threshold'
      value_template: >
        {{state_attr('binary_sensor.kitchen_motion_sensor','threshold')}}

# Living Room Sensor
    living_room_temperature:
      friendly_name: 'Living Room temperature'
      value_template: '{{state_attr("binary_sensor.living_room_motion_sensor", "temperature")}}'
      unit_of_measurement: °C
      device_class: temperature

    living_room_light_level:
      friendly_name: 'Living Room light level'
      value_template: '{{state_attr("binary_sensor.living_room_motion_sensor", "lx")}}'
      unit_of_measurement: lux

    living_room_battery_level:
      friendly_name: 'Living Room battery level'
      value_template: '{{state_attr("binary_sensor.living_room_motion_sensor", "battery")}}'
      unit_of_measurement: '%'

    living_room_motion_sensor_sensitivity:
      friendly_name: 'Living Room sensitivity'
      value_template: >
        {{state_attr('binary_sensor.living_room_motion_sensor','sensitivity')}}

    living_room_motion_sensor_threshold:
      friendly_name: 'Bathroom threshold'
      value_template: >
        {{state_attr('binary_sensor.living_room_motion_sensor','threshold')}}


# Bathroom Sensor  
    bathroom_temperature:
      friendly_name: 'Bathroom temperature'
      value_template: '{{state_attr("binary_sensor.bathroom_motion_sensor", "temperature")}}'
      unit_of_measurement: °C
      device_class: temperature

    bathroom_light_level:
      friendly_name: 'Bathroom light level'
      value_template: '{{state_attr("binary_sensor.bathroom_motion_sensor", "lx")}}'
      unit_of_measurement: lux

    bathroom_battery_level:
      friendly_name: 'Bathroom battery level'
      value_template: '{{state_attr("binary_sensor.bathroom_motion_sensor", "battery")}}'
      unit_of_measurement: '%'

    bathroom_motion_sensor_sensitivity:
      friendly_name: 'Bathroom sensitivity'
      value_template: >
        {{state_attr('binary_sensor.bathroom_motion_sensor','sensitivity')}}

    bathroom_motion_sensor_threshold:
      friendly_name: 'Bathroom threshold'
      value_template: >
        {{state_attr('binary_sensor.bathroom_motion_sensor','threshold')}}

# Hall Sensor

    hall_temperature:
      friendly_name: 'Hall temperature'
      value_template: '{{state_attr("binary_sensor.hall_motion_sensor", "temperature")}}'
      unit_of_measurement: °C
      device_class: temperature

    hall_light_level:
      friendly_name: 'Hall light level'
      value_template: '{{state_attr("binary_sensor.hall_motion_sensor", "lx")}}'
      unit_of_measurement: lux

    hall_battery_level:
      friendly_name: 'Hall battery level'
      value_template: '{{state_attr("binary_sensor.hall_motion_sensor", "battery")}}'
      unit_of_measurement: '%'

    hall_motion_sensor_sensitivity:
      friendly_name: 'Hall sensitivity'
      value_template: >
        {{state_attr('binary_sensor.hall_motion_sensor','sensitivity')}}

    hall_motion_sensor_threshold:
      friendly_name: 'Hall threshold'
      value_template: >
        {{state_attr('binary_sensor.hall_motion_sensor','threshold')}}

# Landing Sensor
    landing_temperature:
      friendly_name: 'Landing temperature'
      value_template: '{{state_attr("binary_sensor.landing_motion_sensor", "temperature")}}'
      unit_of_measurement: °C
      device_class: temperature

    landing_light_level:
      friendly_name: 'Landing light level'
      value_template: '{{state_attr("binary_sensor.landing_motion_sensor", "lx")}}'
      unit_of_measurement: lux

    landing_battery_level:
      friendly_name: 'Landing battery level'
      value_template: '{{state_attr("binary_sensor.landing_motion_sensor", "battery")}}'
      unit_of_measurement: '%' 

    landing_motion_sensor_sensitivity:
      friendly_name: 'Landing sensitivity'
      value_template: >
        {{state_attr('binary_sensor.landing_motion_sensor','sensitivity')}}

    landing_motion_sensor_threshold:
      friendly_name: 'Landing threshold'
      value_template: >
        {{state_attr('binary_sensor.landing_motion_sensor','threshold')}}

# Office Sensor
    office_temperature:
      friendly_name: 'Office temperature'
      value_template: '{{state_attr("binary_sensor.office_motion_sensor", "temperature")}}'
      unit_of_measurement: °C
      device_class: temperature

    office_light_level:
      friendly_name: 'Office light level'
      value_template: '{{state_attr("binary_sensor.office_motion_sensor", "lx")}}'
      unit_of_measurement: lux

    office_battery_level:
      friendly_name: 'Office battery level'
      value_template: '{{state_attr("binary_sensor.office_motion_sensor", "battery")}}'
      unit_of_measurement: '%'

    office_motion_sensor_sensitivity:
      friendly_name: 'Office sensitivity'
      value_template: >
        {{state_attr('binary_sensor.office_motion_sensor','sensitivity')}}

    office_motion_sensor_threshold:
      friendly_name: 'Office threshold'
      value_template: >
        {{state_attr('binary_sensor.office_motion_sensor','threshold')}}

# Bedroom Sensor
    bedroom_temperature:
      friendly_name: 'Bedroom temperature'
      value_template: '{{state_attr("binary_sensor.bedroom_motion_sensor", "temperature")}}'
      unit_of_measurement: °C
      device_class: temperature

    bedroom_light_level:
      friendly_name: 'Bedroom light level'
      value_template: '{{state_attr("binary_sensor.bedroom_motion_sensor", "lx")}}'
      unit_of_measurement: lux

    bedroom_battery_level:
      friendly_name: 'Bedroom battery level'
      value_template: '{{state_attr("binary_sensor.bedroom_motion_sensor", "battery")}}'
      unit_of_measurement: '%'

    bedroom_motion_sensor_sensitivity:
      friendly_name: 'Bedroom sensitivity'
      value_template: >
        {{state_attr('binary_sensor.bedroom_motion_sensor','sensitivity')}}

    bedroom_motion_sensor_threshold:
      friendly_name: 'Bedroom threshold'
      value_template: >
        {{state_attr('binary_sensor.bedroom_motion_sensor','threshold')}}

# Kitchen Hue Remote
    kitchen_switch_battery_level:
      friendly_name: 'Kitchen Remote Battery'
      value_template: '{{state_attr("sensor.kitchen_switch", "battery")}}'
      unit_of_measurement: '%'
    kitchen_remote:
      friendly_name: Hue Kitchen Remote
      value_template: '{% if is_state("sensor.kitchen_switch", "1_click_up") %} 
          Quick Click 1
        {% elif is_state("sensor.kitchen_switch", "1_hold") %}
          Hold Click 1
        {% elif is_state("sensor.kitchen_switch", "2_click_up") %}
          Quick Click 2
        {% elif is_state("sensor.kitchen_switch", "2_hold") %}
          Hold Click 2
        {% elif is_state("sensor.kitchen_switch", "3_click_up") %}
          Quick Click 3
        {% elif is_state("sensor.kitchen_switch", "3_hold") %}
          Hold Click 3
        {% elif is_state("sensor.kitchen_switch", "4_hold") %}
          Hold Click 4
        {% else %}
          Off
        {% endif %}'
# Cupboard Hue Remote
    cupboard_switch_battery_level:
      friendly_name: 'Cupboard Remote Battery'
      value_template: '{{state_attr("sensor.cupboard_switch", "battery")}}'
      unit_of_measurement: '%'        
# Living Room Hue Remote
    living_room_switch_battery_level:
      friendly_name: 'Living Room Remote Battery'
      value_template: '{{state_attr("sensor.living_room_switch", "battery")}}'
      unit_of_measurement: '%'
    living_room_remote:
      friendly_name: Hue Living Room Remote
      value_template: '{% if is_state("sensor.living_room_switch", "1_click_up") %} 
          Christmas Lights
        {% elif is_state("sensor.living_room_switch", "1_click") %}
          Living Room Lamp
        {% elif is_state("sensor.living_room_switch", "1_hold") %}
          Living Room Pendant
        {% elif is_state("sensor.living_room_switch", "2_click_up") %}
          Quick Click 2
        {% elif is_state("sensor.living_room_switch", "2_hold") %}
          Hold Click 2
        {% elif is_state("sensor.living_room_switch", "3_click_up") %}
          Quick Click 3
        {% elif is_state("sensor.living_room_switch", "3_hold") %}
          Hold Click 3
        {% elif is_state("sensor.living_room_switch", "4_hold") %}
          Hold Click 4
        {% else %}
          Off
        {% endif %}'


# Bathroom Hue Remote
    bathroom_switch_battery_level:
      friendly_name: 'Bathroom Remote Battery'
      value_template: '{{state_attr("sensor.bathroom_switch", "battery")}}'
      unit_of_measurement: '%'
    office_remote:
      friendly_name: Hue Bathroom Remote
      value_template: '{% if is_state("sensor.bathroom_switch", "1_click_up") %} 
          Quick Click 1
        {% elif is_state("sensor.bathroom_switch", "1_hold") %}
          Hold Click 1
        {% elif is_state("sensor.bathroom_switch", "2_click_up") %}
          Quick Click 2
        {% elif is_state("sensor.bathroom_switch", "2_hold") %}
          Hold Click 2
        {% elif is_state("sensor.bathroom_switch", "3_click_up") %}
          Quick Click 3
        {% elif is_state("sensor.bathroom_switch", "3_hold") %}
          Hold Click 3
        {% elif is_state("sensor.bathroom_switch", "4_hold") %}
          Hold Click 4
        {% else %}
          Off
        {% endif %}'
# Bedroom Hue Remote
    bedroom_switch_battery_level:
      friendly_name: 'Bedroom Remote Battery'
      value_template: '{{state_attr("sensor.bedroom_switch", "battery")}}'
      unit_of_measurement: '%' 
    bedroom_remote:
      friendly_name: Hue Bedroom Remote
      value_template: '{% if is_state("sensor.bedroom_switch", "1_click_up") %} 
          Quick Click 1
        {% elif is_state("sensor.bedroom_switch", "1_hold") %}
          Hold Click 1
        {% elif is_state("sensor.bedroom_switch", "2_click_up") %}
          Quick Click 2
        {% elif is_state("sensor.bedroom_switch", "2_hold") %}
          Hold Click 2
        {% elif is_state("sensor.bedroom_switch", "3_click_up") %}
          Quick Click 3
        {% elif is_state("sensor.bedroom_switch", "3_hold") %}
          Hold Click 3
        {% elif is_state("sensor.bedroom_switch", "4_hold") %}
          Hold Click 4
        {% else %}
          Off
        {% endif %}'

# Hue Average Temp
- platform: min_max
  type: mean
  name: average_room_temp
  entity_ids:
    - sensor.kitchen_temperature
    - sensor.living_room_temperature
    - sensor.bathroom_temperature
    - sensor.hall_temperature
    - sensor.landing_temperature
    - sensor.office_temperature
    - sensor.bedroom_temperature

# Hue Average LUX
- platform: min_max
  type: mean
  name: average_room_lux
  entity_ids:
    - sensor.kitchen_light_level
    - sensor.living_room_light_level
    - sensor.bathroom_light_level
    - sensor.hall_light_level
    - sensor.landing_light_level
    - sensor.office_light_level
    - sensor.bedroom_light_level