# Wife Status Hangouts Bot Notifications 
- alias: Abi home notification
  trigger:
    platform: state
    entity_id: device_tracker.google_pixel_abi
    to: home
  action:
    service: hangouts.send_message
    data_template:
      target: 
      - id: !secret notifier_noodlemctwoodle
      message: 
        - text: "Abi has arrived home"

- alias: Abi away notification
  trigger:
    platform: state
    entity_id: device_tracker.google_pixel_abi
    to: not_home
  action:
    service: hangouts.send_message
    data_template:
      target: 
      - id: !secret notifier_noodlemctwoodle
      message: 
        - text: "Abi has left home"


# HANotify Notifications
- alias: Abi home notification (Android)
  trigger:
    platform: state
    entity_id: device_tracker.google_pixel_abi
    to: home
  action:
    service: notify.android
    data:
      message: Abi has arrived home

- alias: Abi away notification (Android)
  trigger:
    platform: state
    entity_id: device_tracker.google_pixel_abi
    to: not_home
  action:
    service: notify.android
    data:
      message: "Abi has left home"